#!/system/bin/sh
# Copyright (C) 2013 Canonical Ltd.
#
# Check if ubuntu_command exist
# print the path and exit 0 if found.

FILES=$@

for file in $FILES ; do 
    if [[ -f $file ]] ; then
        echo $file
        exit 1
    fi
done

exit 0
